export const ADD_TO_CART = 'ADD_TO_CART'
export const CLEAR_CART = 'CLEAR_CART'

export const REQUEST_SUCCESS = 'REQUEST_SUCCESS'
export const REQUEST_FAILURE = 'REQUEST_FAILURE'

export const ITEMS_LIST_REQUEST = 'ITEMS_LIST_REQUEST'

export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'

export const LOAD_NEXT_ITEMS = 'LOAD_NEXT_ITEMS'
export const LOAD_PREVIOUS_ITEMS = 'LOAD_PREVIOUS_ITEMS'

export const NAVIGATION_COMPLETE = 'NAVIGATION/COMPLETE'
export const NAVIGATION_START = 'NAVIGATION/START'

export const CHOOSE_FILTER = 'CHOOSE_FILTER'
export const CLEAR_FILTER = 'CLEAR_FILTER'
export const FILTER_SUCCESS = 'FILTER_SUCCESS'
export const FILTER_REQUEST_SUCCESS = 'FILTER_REQUEST_SUCCESS'
export const FILTER_REQUEST_FAILURE = 'FILTER_REQUEST_FAILURE'

export const INPUT_SEARCH_TEXT = 'INPUT_SEARCH_TEXT'
export const SEARCH = 'SEARCH'
