export const ADD_TO_CART = 'ADD_TO_CART'
export const CLEAR_CART = 'CLEAR_CART'

export const ITEMS_LIST_REQUEST = 'ITEMS_LIST_REQUEST'
export const ITEMS_LIST_SUCCESS = 'ITEMS_LIST_SUCCESS'
export const ITEMS_LIST_FAILURE = 'ITEMS_LIST_FAILURE'

export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'

export const LOAD_NEXT_ITEMS = 'LOAD_NEXT_ITEMS'
export const LOAD_PREVIOUS_ITEMS = 'LOAD_PREVIOUS_ITEMS'

export const NAVIGATION_COMPLETE = 'NAVIGATION/COMPLETE'
export const NAVIGATION_START = 'NAVIGATION/START'


export const CATEGORIES_LIST_REQUEST = 'CATEGORIES_LIST_REQUEST'
export const CATEGORIES_LIST_SUCCESS = 'CATEGORIES_LIST_SUCCESS'
export const CATEGORIES_LIST_FAILURE = 'CATEGORIES_LIST_FAILURE'

export const DESIGNERS_LIST_REQUEST = 'DESIGNERS_LIST_REQUEST'
export const DESIGNERS_LIST_SUCCESS = 'DESIGNERS_LIST_SUCCESS'
export const DESIGNERS_LIST_FAILURE = 'DESIGNERS_LIST_FAILURE'

export const CHOOSE_FILTER = 'CHOOSE_FILTER'
export const CLEAR_FILTER = 'CLEAR_FILTER'
export const FILTER_SUCESS = 'FILTER_SUCESS'


export const SEARCH = 'SEARCH'
